name: 'Docker image for Prefect Cloud execution layer on Google Cloud'
branding:
  icon: cloud
  color: blue
description: 'Package your dependencies into a Docker image and push it to Google Artifact Registry'
inputs:
  prefect_api_key:
    description: 'Prefect Cloud API key'
    required: true
  prefect_api_url:
    description: 'Prefect Cloud API URL'
    required: true
  gcp_credentials_json:
    description: 'Content of the Service Account JSON key file'
    required: true
  region:
    description: 'GCP region'
    required: false
    default: 'us-east1'
  artifact_repository:
    description: 'Artifact Registry Repository Name'
    required: false
    default: prefect
  image_name:
    description: 'Artifact Registry Image Name'
    required: false
    default: deployments
  dockerfile_path:
    description: 'Path and filename of the Dockerfile'
    required: false
    default: Dockerfile
  GCS_S3_ENDPOINT:
    description: 'GCS S3 Endpoint'
    required: true
  GCS_ACCESS_KEY:
    description: 'GCS Access Key'
    required: true
  GCS_SECRET:
    description: 'GCS Secret'
    required: true
  GCS_BUCKET_NAME:
    description: 'GCS Bucket Name'
    required: true
  GCS_BUCKET_PATH_BRONZE:
    description: 'GCS Bucket Path Bronze'
    required: true
  GCS_BUCKET_PATH_SILVER:
    description: 'GCS Bucket Path Silver'
    required: true
  GCS_BUCKET_PATH_GOLD:
    description: 'GCS Bucket Path Gold'
    required: true
  BQ_DATASET_NAME:
    description: 'BQ Dataset Name'
    required: true
runs:
  using: "composite"
  steps:
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: "${{ inputs.gcp_credentials_json }}"

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1

    - id: repository
      run: gcloud artifacts repositories create ${{ inputs.artifact_repository }} --repository-format=docker --location=${{ inputs.region }}
      continue-on-error: true
      shell: bash

    - id: set-image
      run: |
        echo "RAW_IMAGE=${{ inputs.region }}-docker.pkg.dev/$GCP_PROJECT/${{ inputs.artifact_repository }}/${{ inputs.image_name }}" >> $GITHUB_ENV
        echo "IMAGE_URI=${{ inputs.region }}-docker.pkg.dev/$GCP_PROJECT/${{ inputs.artifact_repository }}/${{ inputs.image_name }}:$GITHUB_SHA" >> $GITHUB_ENV
        echo "uri=$(echo $IMAGE_URI)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Login to GAR
      uses: docker/login-action@v2
      with:
        registry: '${{ inputs.region }}-docker.pkg.dev'
        username: _json_key
        password: ${{ inputs.gcp_credentials_json }}

    - id: build-image
      run: |
        docker build -q \
        --build-arg PREFECT_API_KEY=${{ inputs.prefect_api_key }} \
        --build-arg PREFECT_API_URL=${{ inputs.prefect_api_url }} \
        
      # Add new build arguments here
        --build-arg GCS_S3_ENDPOINT=${{ inputs.GCS_S3_ENDPOINT }} \
        --build-arg GCS_ACCESS_KEY=${{ inputs.GCS_ACCESS_KEY }} \
        --build-arg GCS_SECRET=${{ inputs.GCS_SECRET }} \
        --build-arg GCS_BUCKET_NAME=${{ inputs.GCS_BUCKET_NAME }} \
        --build-arg GCS_BUCKET_PATH_BRONZE=${{ inputs.GCS_BUCKET_PATH_BRONZE }} \
        --build-arg GCS_BUCKET_PATH_SILVER=${{ inputs.GCS_BUCKET_PATH_SILVER }} \
        --build-arg GCS_BUCKET_PATH_GOLD=${{ inputs.GCS_BUCKET_PATH_GOLD }} \
        --build-arg BQ_DATASET_NAME=${{ inputs.BQ_DATASET_NAME }} \
        -t "${{ env.RAW_IMAGE }}" -f ${{ inputs.dockerfile_path }} .

        docker tag "${{ env.RAW_IMAGE }}" "${{ env.IMAGE_URI }}"
        docker push "${{ env.RAW_IMAGE }}"
        docker push "${{ env.IMAGE_URI }}"
      shell: bash
