repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
  - repo: https://github.com/ambv/black
    rev: 23.7.0  # Use the black release you want to point at
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0  # Use the isort release you want to point at
    hooks:
      - id: isort
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0  # Use the flake8 release you want to point at
    hooks:
      - id: flake8
