FROM prefecthq/prefect:2-python3.10

ENV PYTHONPATH "${PYTHONPATH}:/opt/prefect/"

# Accept build arguments
ARG GCS_S3_ENDPOINT
ARG GCS_ACCESS_KEY
ARG GCS_SECRET
ARG GCS_BUCKET_NAME
ARG GCS_BUCKET_PATH_BRONZE
ARG GCS_BUCKET_PATH_SILVER
ARG GCS_BUCKET_PATH_GOLD
ARG BQ_DATASET_NAME
ARG PREFECT_API_KEY
ARG PREFECT_API_URL

# Set the environment variables within the container
ENV GCS_S3_ENDPOINT=$GCS_S3_ENDPOINT
ENV GCS_ACCESS_KEY=$GCS_ACCESS_KEY
ENV GCS_SECRET=$GCS_SECRET
ENV GCS_BUCKET_NAME=$GCS_BUCKET_NAME
ENV GCS_BUCKET_PATH_BRONZE=$GCS_BUCKET_PATH_BRONZE
ENV GCS_BUCKET_PATH_SILVER=$GCS_BUCKET_PATH_SILVER
ENV GCS_BUCKET_PATH_GOLD=$GCS_BUCKET_PATH_GOLD
ENV BQ_DATASET_NAME=$BQ_DATASET_NAME
ENV PREFECT_API_URL=$PREFECT_API_URL
ENV PREFECT_API_KEY=$PREFECT_API_KEY

ENV PYTHONUNBUFFERED True

# Set a working directory
WORKDIR /opt/prefect

COPY requirements.txt .
COPY setup.py .
COPY src/core core

RUN pip install --upgrade pip setuptools --no-cache-dir
RUN pip --no-cache-dir install -r requirements.txt
RUN pip --no-cache-dir install .

COPY src/flows /opt/prefect/flows

ENTRYPOINT ["prefect", "agent", "start", "-q", "default"]