name: Prefect VM container
on:
  workflow_dispatch:
    inputs:
      artifact_repository:
        description: Artifact Registry Repository
        required: true
        default: 'prefect'
        type: string
      region:
        description: GCP region
        required: true
        default: 'us-east1'
        type: string
      zone:
        description: Zone in the selected GCP region
        required: true
        default: 'us-east1-b'
        type: string
      machine_type:
        description: GCP Compute Engine instance type
        required: true
        default: 'e2-micro'
        type: string
      machine_name:
        description: Unique name for your GCP Compute Engine instance
        required: true
        default: 'prefect-cloud-vm'
        type: string
jobs:
  deploy-container:
    runs-on: ubuntu-latest  
    env:
      GCP_PROJECT_NAME: ${{ secrets.GCP_PROJECT_NAME }}
      GCP_CREDENTIALS_PATH: ${{ secrets.GCP_CREDENTIALS_PATH }}
      GCS_BUCKET_NAME: ${{ secrets.GCS_BUCKET_NAME }}
      GCS_BUCKET_PATH_BRONZE: ${{ secrets.GCS_BUCKET_PATH_BRONZE }}
      GCS_BUCKET_PATH_SILVER: ${{ secrets.GCS_BUCKET_PATH_SILVER }} 
      GCS_BUCKET_PATH_GOLD: ${{ secrets.GCS_BUCKET_PATH_GOLD }} 
      GCS_BUCKET_LOCATION: ${{ secrets.GCS_BUCKET_LOCATION }}    
      GCS_ACCESS_KEY: ${{ secrets.GCS_ACCESS_KEY }}   
      GCS_SECRET: ${{ secrets.GCS_SECRET }}  
      GCS_S3_ENDPOINT: ${{ secrets.GCS_S3_ENDPOINT }}        
    steps:
      - uses: actions/checkout@v3
      - id: deploy-container
        uses: ./.github/actions/deploy-container
        with:
          prefect_api_key: ${{ secrets.PREFECT_API_KEY }}
          prefect_api_url: ${{ secrets.PREFECT_API_URL }}
          artifact_repository: ${{ github.event.inputs.artifact_repository }}  # optional
          region: ${{ github.event.inputs.region }}  # optional
          gcp_credentials_json: ${{ secrets.GCP_CREDENTIALS }}
#          gcp_sa_email: ${{ secrets.GCP_SA_EMAIL }}
          zone: ${{ github.event.inputs.zone }}  # optional
          machine_type: ${{ github.event.inputs.machine_type }}  # optional
          machine_name: ${{ github.event.inputs.machine_name }}  # optional